# Generated by Django 5.0.4 on 2024-06-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('file', models.FileField(upload_to='Files/')),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RIDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jour', models.DateField()),
                ('Prefecture', models.CharField(max_length=100)),
                ('csc', models.CharField(max_length=100)),
                ('TYPE', models.CharField(max_length=100)),
                ('RID_ID', models.CharField(max_length=100)),
                ('STATUT_paquet', models.CharField(max_length=100)),
                ('Commentaire', models.TextField()),
            ],
        ),
    ]
